### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by KailuZhang** [zendesk/android_sdk_demo_apps#44] opened 2019-03-27 08:34 UTC
## Product
Which product does this affect? Add an 'x' in all that apply.
- [x] Support
- [ ] Chat

## Problem
Which type of issue have you encountered? Add an 'x' in all that apply.
- [x] Demo app request
- [ ] Demo app broken
- [ ] Other

## Description
Process: com.vova.android, PID: 32690
    android.view.InflateException: Binary XML file line #18: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
    Caused by: android.view.InflateException: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
        at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.support.design.widget.Snackbar.make(Snackbar.java:188)
        at zendesk.support.request.ComponentError.update(ComponentError.java:54)
        at zendesk.support.request.ComponentError.update(ComponentError.java:20)
        at zendesk.suas.Listeners$StateSelectorListener.update(Listeners.java:68)
        at zendesk.suas.SuasStore.notifyListener(SuasStore.java:73)
        at zendesk.suas.SuasStore.access$400(SuasStore.java:18)
        at zendesk.suas.SuasStore$1$1.next(SuasStore.java:60)
        at zendesk.suas.CombinedMiddleware.loopThroughMiddleware(CombinedMiddleware.java:44)
        at zendesk.suas.CombinedMiddleware.access$000(CombinedMiddleware.java:11)
        at zendesk.suas.CombinedMiddleware$1.next(CombinedMiddleware.java:40)
        at zendesk.support.request.AsyncMiddleware.onAction(AsyncMiddleware.java:48)
        at zendesk.suas.CombinedMiddleware.loopThroughMiddleware(CombinedMiddleware.java:37)
        at zendesk.suas.CombinedMiddleware.onAction(CombinedMiddleware.java:27)
        at zendesk.suas.SuasStore$1.run(SuasStore.java:52)
        at zendesk.suas.Executors$AndroidExecutor.execute(Executors.java:37)
        at zendesk.suas.SuasStore.dispatch(SuasStore.java:48)
        at zendesk.support.request.ActionCreateComment$3.onError(ActionCreateComment.java:184)
        at zendesk.support.ZendeskCallbackSuccess.onError(ZendeskCallbackSuccess.java:22)
        at com.zendesk.service.RetrofitZendeskCallbackAdapter.onFailure(RetrofitZendeskCallbackAdapter.java:77)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$2.run(ExecutorCallAdapterFactory.java:79)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

## Reviewers
@zendesk/adventure-android @zendesk/two-brothers-android @zendesk/ogham @baz8080

**Comment by KailuZhang** [comment] 2019-03-27 11:56
I have found the reason, I used a NoActionBar Theme.

**Comment by tecknut** [comment] 2019-03-28 13:27
Hi @KailuZhang, glad you found the cause of the issue. 

I'm going to close this. Please feel free to open another issue if you have any further trouble.

**Closed by tecknut** 2019-03-28 13:27 UTC
